// ["polish", "first", "scnd", "third"], json model
const config = [
  ["być", "be", "was,were", "been"],
  ["stać się, zostawać kimś/czymś", "become", "became", "become"],
  ["zacząć", "begin", "began", "begun"],
  ["złamać", "break", "broke", "broken"],
  ["przynieść", "bring", "brought", "brought"],
  ["budować", "build", "built", "built"],
  ["kupować", "buy", "bought", "bought"],
  ["spalić", "burn", "burnt", "bunrt"],
  ["złapać", "catch", "caught", "caught"],
  ["wybrać", "choose", "chose", "chosen"],
  ["przyjść", "come", "came", "come"],
  ["kosztować", "cost", "cost", "cost"],
  ["ciąć", "cut", "cut", "cut"],
  ["kopać", "dig", "dug", "dug"],
  ["zrobić", "do", "did", "done"],
  ["zrobić", "make", "made", "made"],
  ["rysować", "draw", "drew", "drawn"],
  ["śnić, marzyć", "dream", "dreamt", "dreamt"],
  ["pić", "drink", "drank", "drunk"],
  ["prowadzić fure", "drive", "drove", "driven"],
  ["jeść", "eat", "ate", "eaten"],
  ["upaść", "fall", "fell", "fallen"],
  ["czuć", "feel", "felt", "felt"],
  ["walczyć", "fight", "fought", "fought"],
  ["znaleźć", "find", "found", "found"],
  ["latać", "fly", "flew", "flown"],
  ["dostać", "get", "got", "got"],
  ["dawać", "give", "gave", "given"],
  ["iść", "go", "went", "gone"],
  ["rosnąć", "grow", "grew", "grown"],
  ["mieć", "have", "had", "had"],
  ["słyszeć", "hear", "heard", "heard"],
  ["uderzać", "hit", "hit", "hit"],
  ["trzymać", "hold", "held", "held"],
  ["ranić, boleć", "hurt", "hurt", "hurt"],
  ["trzymać", "keep", "kept", "kept"],
  ["znać, wiedzieć", "know", "knew", "known"],
  ["uczyć się", "learn", "learnt", "learnt"],
  ["opuścić", "leave", "left", "left"],
  ["pożyczyć", "lend", "lent", "lent"],
  ["zgubić", "lose", "lost", "lost"],
  ["robić, wykonywać", "make", "made", "made"],
  ["znaczyć", "mean", "meant", "meant"],
  ["spotkać", "meet", "met", "met"],
  ["płacić", "pay", "paid", "paid"],
  ["położyć", "put", "put", "put"],
  ["czytać", "read", "read", "read"],
  ["jeździć", "ride", "rode", "ridden"],
  ["dzwonić", "ring", "rang", "rung"],
  ["biec", "run", "ran", "run"],
  ["mówić", "say", "said", "said"],
  ["widzieć", "see", "saw", "seen"],
  ["sprzedać", "sell", "sold", "sold"],
  ["wysłać", "send", "sent", "sent"],
  ["pokazać", "show", "showed", "shown"],
  ["zamykać", "shut", "shut", "shut"],
  ["śpiewać", "sing", "sang", "sung"],
  ["siedzieć", "sit", "sat", "sat"],
  ["spać", "sleep", "slept", "slept"],
  ["mówić", "speak", "spoke", "spoken"],
  ["spędzać, wydawać", "spend", "spent", "spent"],
  ["stać", "stand", "stood", "stood"],
  ["ukraść", "steal", "stole", "stolen"],
  ["pływać", "swim", "swam", "swum"],
  ["brać", "take", "took", "taken"],
  ["uczyć", "teach", "taught", "taught"],
  ["podrzeć", "tear", "tore", "torn"],
  ["powiedzieć", "tell", "told", "told"],
  ["myśleć", "think", "thought", "thought"],
  ["rzucać", "throw", "threw", "thrown"],
  ["budzić", "wake", "woke", "woken"],
  ["nosić", "wear", "wore", "worn"],
  ["rozumieć", "understand", "understood", "understood"],
  ["wygrać", "win", "won", "won"],
  ["pisać", "write", "wrote", "written"],
  ["karmić, żywić", "feed", "fed", "fed"],
  ["walczyć, bić się", "fight", "fought", "fought"],
  ["zapominać", "forget", "forgot", "forgotten"],
  ["wybaczać", "forgive", "forgave", "forgiven"],
  ["chować, ukrywać", "hide", "hid", "hidden"],
  ["prowadzić", "lead", "led", "led"],
  ["obudzić", "wake", "woke", "woken"],
  ["pozwolić", "let", "let", "let"],
  ["rozlać", "spill", "split", "spilt"],
  ["pachnieć", "smell", "smelt", "smelt"],
  ["palić, parzyć, płonąć", "burn", "burned", "burned"],
  ["kopać (np. w ziemi)", "dig", "dug", "dug"],
  ["leżeć", "lie", "lay", "lain"],
  ["zapalać", "light", "lit", "lit"],
  ["świecić", "shine", "shone", "shone"],
  ["ustawić", "set", "set", "set"],
];
export default config;
